import dotenv from "dotenv";
import Book from "../modules/book/book.model.js";
import Category from "../modules/category/category.model.js";
import { connectDB } from "../config/db.js";

dotenv.config();

const seedBooksForAllCategories = async () => {
  try {
    await connectDB();

    // Get all subcategories
    const subcategories = await Category.find({
      parentId: { $exists: true, $ne: null }
    }).select('_id name slug');

    console.log(`📚 Found ${subcategories.length} subcategories`);

    // Books data for each category
    const booksData = {
      'tieu-thuyet': [
        {
          title: "Dấu Chân Hoang Dã",
          slug: "dau-chan-hoang-da",
          description: "Một chuyến đi xuyên miền đất hoang vắng đưa người đọc qua những ký ức dạt dào, những mối quan hệ phức tạp và hành trình tìm lại bản ngã.",
          author: "Nguyễn Minh Quân",
          isbn: "9786041234567",
          price: 185000,
          discountPrice: null,
          currency: "VND",
          quantity: 42,
          sold: 128,
          coverImage: "https://example.com/dau-chan-hoang-da.jpg",
          images: ["https://example.com/dau-chan-hoang-da-1.jpg", "https://example.com/dau-chan-hoang-da-2.jpg"],
          rating: 4.7,
          reviewCount: 58,
          publisher: "Nhà xuất bản Trẻ",
          publishedDate: new Date("2023-05-10"),
          pages: 304,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["tiểu thuyết", "hành trình", "tự tìm mình"],
          tags: ["hoang-da", "tieu-thuyet", "van-hoc"],
          sortOrder: 1,
        },
        {
          title: "Mùa Hoa Cuối Cùng",
          slug: "mua-hoa-cuoi-cung",
          description: "Câu chuyện tình cảm sâu lắng của hai con người bước qua tổn thương và tìm lại bình yên trong mùa hoa cuối cùng của đời mình.",
          author: "Thanh Hương",
          isbn: "9786049876543",
          price: 168000,
          discountPrice: null,
          currency: "VND",
          quantity: 58,
          sold: 210,
          coverImage: "https://example.com/mua-hoa-cuoi-cung.jpg",
          images: ["https://example.com/mua-hoa-cuoi-cung-1.jpg", "https://example.com/mua-hoa-cuoi-cung-2.jpg"],
          rating: 4.5,
          reviewCount: 76,
          publisher: "Nhà xuất bản Văn hóa - Văn nghệ",
          publishedDate: new Date("2024-01-18"),
          pages: 276,
          language: "VI",
          edition: "2nd edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["tình yêu", "tiểu thuyết Việt Nam", "đời sống"],
          tags: ["tinh-yeu", "mua-hoa", "tieu-thuyet"],
          sortOrder: 2,
        },
        {
          title: "Bến Bờ Ký Ức",
          slug: "ben-bo-ky-uc",
          description: "Tác phẩm mở ra những ngày hè trên bến sông, khi ký ức và lời hứa chập chờn trong trái tim của những người trẻ giữa cơn gió thay đổi.",
          author: "Lê Thị Kim",
          isbn: "9786045647382",
          price: 172000,
          discountPrice: 145000,
          currency: "VND",
          quantity: 35,
          sold: 95,
          coverImage: "https://example.com/ben-bo-ky-uc.jpg",
          images: ["https://example.com/ben-bo-ky-uc-1.jpg", "https://example.com/ben-bo-ky-uc-2.jpg"],
          rating: 4.3,
          reviewCount: 34,
          publisher: "Nhà xuất bản Hội Nhà văn",
          publishedDate: new Date("2022-08-22"),
          pages: 252,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["ký ức", "bến bờ", "tiểu thuyết"],
          tags: ["ben-bo", "ky-uc", "van-hoc"],
          sortOrder: 3,
        },
        {
          title: "Con Mắt Của Thành Phố",
          slug: "con-mat-cua-thanh-pho",
          description: "Một bức tranh đô thị với những góc khuất, cuộc đời mưu sinh, và con mắt tinh tế của người quan sát giữa nhịp sống không ngừng.",
          author: "Hoàng Kiên",
          isbn: "9786043219876",
          price: 190000,
          discountPrice: 170000,
          currency: "VND",
          quantity: 48,
          sold: 142,
          coverImage: "https://example.com/con-mat-cua-thanh-pho.jpg",
          images: ["https://example.com/con-mat-cua-thanh-pho-1.jpg", "https://example.com/con-mat-cua-thanh-pho-2.jpg"],
          rating: 4.6,
          reviewCount: 61,
          publisher: "Nhà xuất bản Phụ Nữ",
          publishedDate: new Date("2023-11-05"),
          pages: 318,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: true,
          isDiscount: true,
          keywords: ["thành phố", "nhịp sống", "tiểu thuyết đô thị"],
          tags: ["thanh-pho", "doi-song", "tieu-thuyet"],
          sortOrder: 4,
        },
        {
          title: "Thành Phố Không Ngủ",
          slug: "thanh-pho-khong-ngu",
          description: "Hành trình tinh thần của những con người lạc lõng giữa thành phố sôi động, nơi tiếng ồn và ánh đèn không bao giờ tắt.",
          author: "Phạm Nhật Vinh",
          isbn: "9786048765431",
          price: 164000,
          discountPrice: null,
          currency: "VND",
          quantity: 53,
          sold: 187,
          coverImage: "https://example.com/thanh-pho-khong-ngu.jpg",
          images: ["https://example.com/thanh-pho-khong-ngu-1.jpg", "https://example.com/thanh-pho-khong-ngu-2.jpg"],
          rating: 4.4,
          reviewCount: 49,
          publisher: "Nhà xuất bản Văn Nghệ",
          publishedDate: new Date("2024-02-14"),
          pages: 288,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["đô thị", "cô đơn", "tiểu thuyết"],
          tags: ["khong-ngu", "do-thi", "tieu-thuyet"],
          sortOrder: 5,
        },
        {
          title: "Cơn Mưa Qua Ngã Tư",
          slug: "con-mua-qua-nga-tu",
          description: "Một ngày mưa bão trên ngã tư phố cổ, nơi những cuộc gặp gỡ bất ngờ thay đổi định mệnh và mở ra những bí mật chưa kể.",
          author: "Trần Khải",
          isbn: "9786049988770",
          price: 176000,
          discountPrice: 152000,
          currency: "VND",
          quantity: 39,
          sold: 132,
          coverImage: "https://example.com/con-mua-qua-nga-tu.jpg",
          images: ["https://example.com/con-mua-qua-nga-tu-1.jpg", "https://example.com/con-mua-qua-nga-tu-2.jpg"],
          rating: 4.2,
          reviewCount: 28,
          publisher: "Nhà xuất bản Kim Đồng",
          publishedDate: new Date("2023-09-30"),
          pages: 264,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["mưa", "ngã tư", "tiểu thuyết cảm xúc"],
          tags: ["con-mua", "nga-tu", "tieu-thuyet"],
          sortOrder: 6,
        },
      ],
      'truyen-ngan': [
        {
          title: "Những Câu Chuyện Ngắn",
          slug: "nhung-cau-chuyen-ngan",
          description: "Tuyển tập những câu chuyện ngắn sâu sắc về cuộc sống, tình yêu và những khoảnh khắc đáng nhớ.",
          author: "Nguyễn Minh Châu",
          isbn: "9786041111111",
          price: 125000,
          discountPrice: null,
          currency: "VND",
          quantity: 67,
          sold: 89,
          coverImage: "https://example.com/nhung-cau-chuyen-ngan.jpg",
          images: ["https://example.com/nhung-cau-chuyen-ngan-1.jpg"],
          rating: 4.4,
          reviewCount: 42,
          publisher: "Nhà xuất bản Văn Học",
          publishedDate: new Date("2022-03-15"),
          pages: 198,
          language: "VI",
          edition: "Tuyển tập",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: false,
          keywords: ["truyện ngắn", "tuyển tập", "cuộc sống"],
          tags: ["truyen-ngan", "tuyen-tap", "van-hoc"],
          sortOrder: 1,
        },
        {
          title: "Đêm Trắng",
          slug: "dem-trang",
          description: "Những câu chuyện ngắn về những đêm trắng không ngủ, những suy tư và những cảm xúc thầm kín.",
          author: "Lê Minh",
          isbn: "9786042222222",
          price: 118000,
          discountPrice: 99000,
          currency: "VND",
          quantity: 45,
          sold: 67,
          coverImage: "https://example.com/dem-trang.jpg",
          images: ["https://example.com/dem-trang-1.jpg"],
          rating: 4.2,
          reviewCount: 31,
          publisher: "Nhà xuất bản Hội Nhà Văn",
          publishedDate: new Date("2023-07-20"),
          pages: 176,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["đêm trắng", "truyện ngắn", "suy tư"],
          tags: ["dem-trang", "truyen-ngan", "suy-tu"],
          sortOrder: 2,
        },
        {
          title: "Những Mảnh Ghép Cuộc Đời",
          slug: "nhung-manh-ghep-cuoc-doi",
          description: "Tuyển tập truyện ngắn kể về những mảnh ghép cuộc đời, những câu chuyện nhỏ nhưng đầy ý nghĩa.",
          author: "Trần Thị Lan",
          isbn: "9786043333333",
          price: 132000,
          discountPrice: null,
          currency: "VND",
          quantity: 52,
          sold: 78,
          coverImage: "https://example.com/nhung-manh-ghep.jpg",
          images: ["https://example.com/nhung-manh-ghep-1.jpg"],
          rating: 4.5,
          reviewCount: 55,
          publisher: "Nhà xuất bản Phụ Nữ",
          publishedDate: new Date("2023-12-08"),
          pages: 224,
          language: "VI",
          edition: "Tuyển tập",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["mảnh ghép", "cuộc đời", "truyện ngắn"],
          tags: ["manh-ghep", "cuoc-doi", "truyen-ngan"],
          sortOrder: 3,
        },
        {
          title: "Góc Phố Vắng",
          slug: "goc-pho-vang",
          description: "Những câu chuyện ngắn diễn ra ở những góc phố vắng, nơi những số phận chạm nhau trong im lặng.",
          author: "Phạm Văn Đức",
          isbn: "9786044444444",
          price: 115000,
          discountPrice: 97000,
          currency: "VND",
          quantity: 38,
          sold: 54,
          coverImage: "https://example.com/goc-pho-vang.jpg",
          images: ["https://example.com/goc-pho-vang-1.jpg"],
          rating: 4.1,
          reviewCount: 27,
          publisher: "Nhà xuất bản Văn Nghệ",
          publishedDate: new Date("2022-11-12"),
          pages: 168,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["góc phố", "truyện ngắn", "số phận"],
          tags: ["goc-pho", "truyen-ngan", "so-phan"],
          sortOrder: 4,
        },
        {
          title: "Những Bông Hoa Dại",
          slug: "nhung-bong-hoa-dai",
          description: "Tuyển tập truyện ngắn về những bông hoa dại, những câu chuyện giản dị nhưng đầy cảm xúc.",
          author: "Nguyễn Thị Mai",
          isbn: "9786045555555",
          price: 128000,
          discountPrice: null,
          currency: "VND",
          quantity: 41,
          sold: 63,
          coverImage: "https://example.com/nhung-bong-hoa-dai.jpg",
          images: ["https://example.com/nhung-bong-hoa-dai-1.jpg"],
          rating: 4.3,
          reviewCount: 38,
          publisher: "Nhà xuất bản Kim Đồng",
          publishedDate: new Date("2024-01-25"),
          pages: 192,
          language: "VI",
          edition: "Tuyển tập",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: true,
          isDiscount: false,
          keywords: ["hoa dại", "truyện ngắn", "cảm xúc"],
          tags: ["hoa-dai", "truyen-ngan", "cam-xuc"],
          sortOrder: 5,
        },
        {
          title: "Chuyến Đi Về Quá Khứ",
          slug: "chuyen-di-ve-qua-khu",
          description: "Những câu chuyện ngắn đưa người đọc trở về quá khứ, nơi những ký ức sống động và những bài học cuộc sống.",
          author: "Hoàng Văn Tùng",
          isbn: "9786046666666",
          price: 122000,
          discountPrice: 103000,
          currency: "VND",
          quantity: 49,
          sold: 71,
          coverImage: "https://example.com/chuyen-di-ve-qua-khu.jpg",
          images: ["https://example.com/chuyen-di-ve-qua-khu-1.jpg"],
          rating: 4.4,
          reviewCount: 44,
          publisher: "Nhà xuất bản Trẻ",
          publishedDate: new Date("2023-08-18"),
          pages: 208,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: true,
          keywords: ["quá khứ", "ký ức", "truyện ngắn"],
          tags: ["qua-khu", "ky-uc", "truyen-ngan"],
          sortOrder: 6,
        },
      ],
      'ngon-tinh': [
        {
          title: "Mãi Mãi Bên Nhau",
          slug: "mai-mai-ben-nhau",
          description: "Câu chuyện tình yêu ngọt ngào về hai người yêu nhau từ thuở thiếu thời, vượt qua bao sóng gió để mãi bên nhau.",
          author: "Lan Anh",
          isbn: "9786047777777",
          price: 145000,
          discountPrice: null,
          currency: "VND",
          quantity: 73,
          sold: 156,
          coverImage: "https://example.com/mai-mai-ben-nhau.jpg",
          images: ["https://example.com/mai-mai-ben-nhau-1.jpg"],
          rating: 4.6,
          reviewCount: 89,
          publisher: "Nhà xuất bản Phụ Nữ",
          publishedDate: new Date("2023-02-14"),
          pages: 312,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["ngôn tình", "tình yêu", "ngọt ngào"],
          tags: ["ngon-tinh", "tinh-yeu", "ngot-ngao"],
          sortOrder: 1,
        },
        {
          title: "Lời Hứa Dưới Ánh Trăng",
          slug: "loi-hua-duoi-anh-trang",
          description: "Một câu chuyện tình lãng mạn về lời hứa dưới ánh trăng, nơi tình yêu được thử thách qua thời gian.",
          author: "Minh Thu",
          isbn: "9786048888888",
          price: 138000,
          discountPrice: 116000,
          currency: "VND",
          quantity: 58,
          sold: 124,
          coverImage: "https://example.com/loi-hua-duoi-anh-trang.jpg",
          images: ["https://example.com/loi-hua-duoi-anh-trang-1.jpg"],
          rating: 4.4,
          reviewCount: 67,
          publisher: "Nhà xuất bản Văn Học",
          publishedDate: new Date("2024-03-08"),
          pages: 288,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: true,
          keywords: ["lời hứa", "ánh trăng", "ngôn tình"],
          tags: ["loi-hua", "anh-trang", "ngon-tinh"],
          sortOrder: 2,
        },
        {
          title: "Tình Yêu Trong Sương Mù",
          slug: "tinh-yeu-trong-suong-mu",
          description: "Câu chuyện tình yêu đầy bí ẩn và lãng mạn giữa sương mù, nơi hai trái tim tìm thấy nhau trong u ám.",
          author: "Hương Giang",
          isbn: "9786049999999",
          price: 142000,
          discountPrice: null,
          currency: "VND",
          quantity: 64,
          sold: 98,
          coverImage: "https://example.com/tinh-yeu-trong-suong-mu.jpg",
          images: ["https://example.com/tinh-yeu-trong-suong-mu-1.jpg"],
          rating: 4.3,
          reviewCount: 52,
          publisher: "Nhà xuất bản Hội Nhà Văn",
          publishedDate: new Date("2022-09-22"),
          pages: 276,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: false,
          keywords: ["sương mù", "bí ẩn", "ngôn tình"],
          tags: ["suong-mu", "bi-an", "ngon-tinh"],
          sortOrder: 3,
        },
        {
          title: "Hoa Tím Dưới Ánh Mặt Trời",
          slug: "hoa-tim-duoi-anh-mat-troi",
          description: "Một câu chuyện tình yêu trong sáng như hoa tím, nở rộ dưới ánh mặt trời và mang lại niềm vui bất tận.",
          author: "Thúy Vi",
          isbn: "9786040000000",
          price: 135000,
          discountPrice: 114000,
          currency: "VND",
          quantity: 51,
          sold: 87,
          coverImage: "https://example.com/hoa-tim-duoi-anh-mat-troi.jpg",
          images: ["https://example.com/hoa-tim-duoi-anh-mat-troi-1.jpg"],
          rating: 4.5,
          reviewCount: 71,
          publisher: "Nhà xuất bản Kim Đồng",
          publishedDate: new Date("2023-06-12"),
          pages: 264,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["hoa tím", "mặt trời", "ngôn tình"],
          tags: ["hoa-tim", "mat-troi", "ngon-tinh"],
          sortOrder: 4,
        },
        {
          title: "Tình Yêu Qua Những Trang Sách",
          slug: "tinh-yeu-qua-nhung-trang-sach",
          description: "Câu chuyện tình yêu lãng mạn bắt đầu từ những trang sách, nơi hai tâm hồn đồng điệu tìm thấy nhau.",
          author: "Ngọc Anh",
          isbn: "9786041111112",
          price: 148000,
          discountPrice: null,
          currency: "VND",
          quantity: 69,
          sold: 134,
          coverImage: "https://example.com/tinh-yeu-qua-nhung-trang-sach.jpg",
          images: ["https://example.com/tinh-yeu-qua-nhung-trang-sach-1.jpg"],
          rating: 4.7,
          reviewCount: 93,
          publisher: "Nhà xuất bản Văn Nghệ",
          publishedDate: new Date("2024-04-05"),
          pages: 298,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["trang sách", "đồng điệu", "ngôn tình"],
          tags: ["trang-sach", "dong-dieu", "ngon-tinh"],
          sortOrder: 5,
        },
        {
          title: "Mùa Thu Tình Yêu",
          slug: "mua-thu-tinh-yeu",
          description: "Câu chuyện tình yêu dịu dàng như mùa thu, nơi lá vàng rơi và tình cảm nảy nở trong không khí se lạnh.",
          author: "Bích Hà",
          isbn: "9786042222223",
          price: 139000,
          discountPrice: 118000,
          currency: "VND",
          quantity: 56,
          sold: 102,
          coverImage: "https://example.com/mua-thu-tinh-yeu.jpg",
          images: ["https://example.com/mua-thu-tinh-yeu-1.jpg"],
          rating: 4.4,
          reviewCount: 58,
          publisher: "Nhà xuất bản Trẻ",
          publishedDate: new Date("2023-10-28"),
          pages: 272,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["mùa thu", "lá vàng", "ngôn tình"],
          tags: ["mua-thu", "la-vang", "ngon-tinh"],
          sortOrder: 6,
        },
      ],
      'van-hoc-viet-nam': [
        {
          title: "Tắt Đèn",
          slug: "tat-den",
          description: "Tác phẩm kinh điển của văn học Việt Nam, kể về số phận của người phụ nữ trong xã hội phong kiến.",
          author: "Ngô Tất Tố",
          isbn: "9786043333334",
          price: 95000,
          discountPrice: null,
          currency: "VND",
          quantity: 89,
          sold: 167,
          coverImage: "https://example.com/tat-den.jpg",
          images: ["https://example.com/tat-den-1.jpg"],
          rating: 4.8,
          reviewCount: 124,
          publisher: "Nhà xuất bản Giáo Dục",
          publishedDate: new Date("1946-01-01"),
          pages: 156,
          language: "VI",
          edition: "Tái bản 2023",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["Ngô Tất Tố", "văn học Việt Nam", "phong kiến"],
          tags: ["ngo-tat-to", "van-hoc-viet-nam", "phong-kien"],
          sortOrder: 1,
        },
        {
          title: "Vợ Nhặt",
          slug: "vo-nhat",
          description: "Truyện ngắn kinh điển của Kim Lân, phản ánh cuộc sống của người nông dân Việt Nam trước Cách mạng.",
          author: "Kim Lân",
          isbn: "9786044444445",
          price: 78000,
          discountPrice: 65000,
          currency: "VND",
          quantity: 76,
          sold: 143,
          coverImage: "https://example.com/vo-nhat.jpg",
          images: ["https://example.com/vo-nhat-1.jpg"],
          rating: 4.6,
          reviewCount: 98,
          publisher: "Nhà xuất bản Văn Học",
          publishedDate: new Date("1960-01-01"),
          pages: 89,
          language: "VI",
          edition: "Tái bản 2022",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: true,
          keywords: ["Kim Lân", "truyện ngắn", "nông dân"],
          tags: ["kim-lan", "truyen-ngan", "nong-dan"],
          sortOrder: 2,
        },
        {
          title: "Chiếc Thuyền Ngoài Xa",
          slug: "chiec-thuyen-ngoai-xa",
          description: "Tác phẩm xuất sắc của Nguyễn Minh Châu, kể về những chuyến đi biển đầy gian nan của ngư dân.",
          author: "Nguyễn Minh Châu",
          isbn: "9786045555556",
          price: 112000,
          discountPrice: null,
          currency: "VND",
          quantity: 67,
          sold: 125,
          coverImage: "https://example.com/chiec-thuyen-ngoai-xa.jpg",
          images: ["https://example.com/chiec-thuyen-ngoai-xa-1.jpg"],
          rating: 4.7,
          reviewCount: 87,
          publisher: "Nhà xuất bản Hội Nhà Văn",
          publishedDate: new Date("1980-01-01"),
          pages: 234,
          language: "VI",
          edition: "Tái bản 2021",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["Nguyễn Minh Châu", "ngư dân", "biển cả"],
          tags: ["nguyen-minh-chau", "ngu-dan", "bien-ca"],
          sortOrder: 3,
        },
        {
          title: "Đọc Tiểu Thanh Ký",
          slug: "doc-tieu-thanh-ky",
          description: "Tuyển tập truyện ngắn của Nguyễn Du, một trong những tác phẩm kinh điển của văn học Việt Nam.",
          author: "Nguyễn Du",
          isbn: "9786046666667",
          price: 135000,
          discountPrice: 114000,
          currency: "VND",
          quantity: 54,
          sold: 96,
          coverImage: "https://example.com/doc-tieu-thanh-ky.jpg",
          images: ["https://example.com/doc-tieu-thanh-ky-1.jpg"],
          rating: 4.5,
          reviewCount: 73,
          publisher: "Nhà xuất bản Giáo Dục",
          publishedDate: new Date("1820-01-01"),
          pages: 189,
          language: "VI",
          edition: "Tái bản 2023",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["Nguyễn Du", "Truyện Kiều", "kinh điển"],
          tags: ["nguyen-du", "truyen-kieu", "kinh-dien"],
          sortOrder: 4,
        },
        {
          title: "Những Ngày Thơ Ấu",
          slug: "nhung-ngay-tho-au",
          description: "Hồi ức thơ mộng về những ngày thơ ấu của Nguyễn Nhật Ánh, một phần của văn học thiếu nhi Việt Nam.",
          author: "Nguyễn Nhật Ánh",
          isbn: "9786047777778",
          price: 98000,
          discountPrice: null,
          currency: "VND",
          quantity: 82,
          sold: 154,
          coverImage: "https://example.com/nhung-ngay-tho-au.jpg",
          images: ["https://example.com/nhung-ngay-tho-au-1.jpg"],
          rating: 4.4,
          reviewCount: 112,
          publisher: "Nhà xuất bản Trẻ",
          publishedDate: new Date("1990-01-01"),
          pages: 167,
          language: "VI",
          edition: "Tái bản 2024",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["Nguyễn Nhật Ánh", "thơ ấu", "thiếu nhi"],
          tags: ["nguyen-nhat-anh", "tho-au", "thieu-nhi"],
          sortOrder: 5,
        },
        {
          title: "Đất Mẹ",
          slug: "dat-me",
          description: "Tác phẩm kinh điển của Nguyễn Minh Châu, ca ngợi tình yêu quê hương đất mẹ.",
          author: "Nguyễn Minh Châu",
          isbn: "9786048888889",
          price: 108000,
          discountPrice: 91000,
          currency: "VND",
          quantity: 61,
          sold: 118,
          coverImage: "https://example.com/dat-me.jpg",
          images: ["https://example.com/dat-me-1.jpg"],
          rating: 4.6,
          reviewCount: 85,
          publisher: "Nhà xuất bản Hội Nhà Văn",
          publishedDate: new Date("1975-01-01"),
          pages: 198,
          language: "VI",
          edition: "Tái bản 2022",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["Nguyễn Minh Châu", "đất mẹ", "quê hương"],
          tags: ["nguyen-minh-chau", "dat-me", "que-huong"],
          sortOrder: 6,
        },
      ],
      'dau-tu': [
        {
          title: "Chiến Lược Đầu Tư Thông Minh",
          slug: "chien-luoc-dau-tu-thong-minh",
          description: "Hướng dẫn chi tiết về các chiến lược đầu tư hiệu quả trong thị trường tài chính hiện đại.",
          author: "Nguyễn Văn A",
          isbn: "9786049999990",
          price: 285000,
          discountPrice: null,
          currency: "VND",
          quantity: 34,
          sold: 67,
          coverImage: "https://example.com/chien-luoc-dau-tu.jpg",
          images: ["https://example.com/chien-luoc-dau-tu-1.jpg"],
          rating: 4.3,
          reviewCount: 45,
          publisher: "Nhà xuất bản Tài Chính",
          publishedDate: new Date("2023-01-15"),
          pages: 356,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["đầu tư", "chiến lược", "tài chính"],
          tags: ["dau-tu", "chien-luoc", "tai-chinh"],
          sortOrder: 1,
        },
        {
          title: "Đầu Tư Bất Động Sản",
          slug: "dau-tu-bat-dong-san",
          description: "Cẩm nang đầy đủ về đầu tư bất động sản, từ chọn lựa đến quản lý và bán ra.",
          author: "Trần Thị B",
          isbn: "9786040000001",
          price: 320000,
          discountPrice: 272000,
          currency: "VND",
          quantity: 28,
          sold: 52,
          coverImage: "https://example.com/dau-tu-bat-dong-san.jpg",
          images: ["https://example.com/dau-tu-bat-dong-san-1.jpg"],
          rating: 4.5,
          reviewCount: 38,
          publisher: "Nhà xuất bản Xây Dựng",
          publishedDate: new Date("2023-06-20"),
          pages: 412,
          language: "VI",
          edition: "2nd edition",
          format: "hardcover",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["bất động sản", "đầu tư", "quản lý"],
          tags: ["bat-dong-san", "dau-tu", "quan-ly"],
          sortOrder: 2,
        },
        {
          title: "Đầu Tư Chứng Khoán Cơ Bản",
          slug: "dau-tu-chung-khoan-co-ban",
          description: "Hướng dẫn từ A đến Z về đầu tư chứng khoán cho người mới bắt đầu.",
          author: "Lê Văn C",
          isbn: "9786041111113",
          price: 265000,
          discountPrice: null,
          currency: "VND",
          quantity: 41,
          sold: 78,
          coverImage: "https://example.com/dau-tu-chung-khoan.jpg",
          images: ["https://example.com/dau-tu-chung-khoan-1.jpg"],
          rating: 4.2,
          reviewCount: 56,
          publisher: "Nhà xuất bản Tài Chính",
          publishedDate: new Date("2024-02-10"),
          pages: 298,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["chứng khoán", "đầu tư", "người mới"],
          tags: ["chung-khoan", "dau-tu", "nguoi-moi"],
          sortOrder: 3,
        },
        {
          title: "Đầu Tư Vàng Và Ngoại Tệ",
          slug: "dau-tu-vang-va-ngoai-te",
          description: "Chiến lược đầu tư vào vàng và ngoại tệ trong bối cảnh kinh tế toàn cầu.",
          author: "Phạm Thị D",
          isbn: "9786042222224",
          price: 295000,
          discountPrice: 251000,
          currency: "VND",
          quantity: 31,
          sold: 43,
          coverImage: "https://example.com/dau-tu-vang-ngoai-te.jpg",
          images: ["https://example.com/dau-tu-vang-ngoai-te-1.jpg"],
          rating: 4.4,
          reviewCount: 32,
          publisher: "Nhà xuất bản Ngoại Thương",
          publishedDate: new Date("2023-09-05"),
          pages: 334,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["vàng", "ngoại tệ", "toàn cầu"],
          tags: ["vang", "ngoai-te", "toan-cau"],
          sortOrder: 4,
        },
        {
          title: "Đầu Tư Crypto",
          slug: "dau-tu-crypto",
          description: "Hướng dẫn đầu tư tiền điện tử và các tài sản số trong thời đại kỹ thuật số.",
          author: "Hoàng Văn E",
          isbn: "9786043333335",
          price: 275000,
          discountPrice: null,
          currency: "VND",
          quantity: 37,
          sold: 69,
          coverImage: "https://example.com/dau-tu-crypto.jpg",
          images: ["https://example.com/dau-tu-crypto-1.jpg"],
          rating: 4.1,
          reviewCount: 41,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2024-01-18"),
          pages: 276,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["crypto", "tiền điện tử", "kỹ thuật số"],
          tags: ["crypto", "tien-dien-tu", "ky-thuat-so"],
          sortOrder: 5,
        },
        {
          title: "Quản Lý Rủi Ro Đầu Tư",
          slug: "quan-ly-rui-ro-dau-tu",
          description: "Các phương pháp quản lý và giảm thiểu rủi ro trong hoạt động đầu tư tài chính.",
          author: "Nguyễn Thị F",
          isbn: "9786044444446",
          price: 310000,
          discountPrice: 264000,
          currency: "VND",
          quantity: 25,
          sold: 38,
          coverImage: "https://example.com/quan-ly-rui-ro.jpg",
          images: ["https://example.com/quan-ly-rui-ro-1.jpg"],
          rating: 4.6,
          reviewCount: 29,
          publisher: "Nhà xuất bản Tài Chính",
          publishedDate: new Date("2023-11-12"),
          pages: 368,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["rủi ro", "quản lý", "đầu tư"],
          tags: ["rui-ro", "quan-ly", "dau-tu"],
          sortOrder: 6,
        },
      ],
      'marketing': [
        {
          title: "Marketing 4.0",
          slug: "marketing-4-0",
          description: "Chiến lược marketing trong kỷ nguyên số, ứng dụng công nghệ và dữ liệu để kết nối với khách hàng.",
          author: "Philip Kotler",
          isbn: "9786045555557",
          price: 350000,
          discountPrice: null,
          currency: "VND",
          quantity: 22,
          sold: 45,
          coverImage: "https://example.com/marketing-4-0.jpg",
          images: ["https://example.com/marketing-4-0-1.jpg"],
          rating: 4.7,
          reviewCount: 67,
          publisher: "Nhà xuất bản Kinh Tế",
          publishedDate: new Date("2022-08-15"),
          pages: 412,
          language: "VI",
          edition: "Dịch Việt",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["marketing", "kỷ nguyên số", "khách hàng"],
          tags: ["marketing", "ky-nguyen-so", "khach-hang"],
          sortOrder: 1,
        },
        {
          title: "Digital Marketing Cơ Bản",
          slug: "digital-marketing-co-ban",
          description: "Hướng dẫn toàn diện về marketing số từ SEO, SEM đến social media marketing.",
          author: "Nguyễn Văn G",
          isbn: "9786046666668",
          price: 285000,
          discountPrice: 242000,
          currency: "VND",
          quantity: 35,
          sold: 78,
          coverImage: "https://example.com/digital-marketing.jpg",
          images: ["https://example.com/digital-marketing-1.jpg"],
          rating: 4.4,
          reviewCount: 89,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2023-03-22"),
          pages: 334,
          language: "VI",
          edition: "2nd edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: true,
          keywords: ["digital marketing", "SEO", "social media"],
          tags: ["digital-marketing", "seo", "social-media"],
          sortOrder: 2,
        },
        {
          title: "Content Marketing",
          slug: "content-marketing",
          description: "Chiến lược tạo và phân phối nội dung giá trị để thu hút và giữ chân khách hàng.",
          author: "Trần Thị H",
          isbn: "9786047777779",
          price: 265000,
          discountPrice: null,
          currency: "VND",
          quantity: 28,
          sold: 56,
          coverImage: "https://example.com/content-marketing.jpg",
          images: ["https://example.com/content-marketing-1.jpg"],
          rating: 4.3,
          reviewCount: 43,
          publisher: "Nhà xuất bản Marketing",
          publishedDate: new Date("2024-01-08"),
          pages: 298,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: true,
          isDiscount: false,
          keywords: ["content marketing", "nội dung", "khách hàng"],
          tags: ["content-marketing", "noi-dung", "khach-hang"],
          sortOrder: 3,
        },
        {
          title: "Brand Management",
          slug: "brand-management",
          description: "Quản lý thương hiệu toàn diện từ xây dựng, phát triển đến bảo vệ giá trị thương hiệu.",
          author: "Lê Văn I",
          isbn: "9786048888890",
          price: 320000,
          discountPrice: 272000,
          currency: "VND",
          quantity: 19,
          sold: 34,
          coverImage: "https://example.com/brand-management.jpg",
          images: ["https://example.com/brand-management-1.jpg"],
          rating: 4.5,
          reviewCount: 28,
          publisher: "Nhà xuất bản Kinh Tế",
          publishedDate: new Date("2023-07-14"),
          pages: 376,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["brand management", "thương hiệu", "quản lý"],
          tags: ["brand-management", "thuong-hieu", "quan-ly"],
          sortOrder: 4,
        },
        {
          title: "Marketing Trên Mạng Xã Hội",
          slug: "marketing-tren-mang-xa-hoi",
          description: "Chiến lược marketing hiệu quả trên các nền tảng mạng xã hội phổ biến.",
          author: "Phạm Thị K",
          isbn: "9786049999991",
          price: 245000,
          discountPrice: null,
          currency: "VND",
          quantity: 42,
          sold: 87,
          coverImage: "https://example.com/marketing-mang-xa-hoi.jpg",
          images: ["https://example.com/marketing-mang-xa-hoi-1.jpg"],
          rating: 4.2,
          reviewCount: 65,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2024-02-28"),
          pages: 256,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["mạng xã hội", "marketing", "nền tảng"],
          tags: ["mang-xa-hoi", "marketing", "nen-tang"],
          sortOrder: 5,
        },
        {
          title: "Email Marketing",
          slug: "email-marketing",
          description: "Hướng dẫn chi tiết về chiến lược email marketing hiệu quả để tăng doanh số.",
          author: "Hoàng Văn L",
          isbn: "9786040000002",
          price: 235000,
          discountPrice: 200000,
          currency: "VND",
          quantity: 31,
          sold: 52,
          coverImage: "https://example.com/email-marketing.jpg",
          images: ["https://example.com/email-marketing-1.jpg"],
          rating: 4.1,
          reviewCount: 37,
          publisher: "Nhà xuất bản Marketing",
          publishedDate: new Date("2023-10-20"),
          pages: 224,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["email marketing", "doanh số", "chiến lược"],
          tags: ["email-marketing", "doanh-so", "chien-luoc"],
          sortOrder: 6,
        },
      ],
      'khoi-nghiep': [
        {
          title: "Lean Startup",
          slug: "lean-startup",
          description: "Phương pháp khởi nghiệp tinh gọn, xây dựng sản phẩm MVP và phát triển doanh nghiệp hiệu quả.",
          author: "Eric Ries",
          isbn: "9786041111114",
          price: 295000,
          discountPrice: null,
          currency: "VND",
          quantity: 26,
          sold: 67,
          coverImage: "https://example.com/lean-startup.jpg",
          images: ["https://example.com/lean-startup-1.jpg"],
          rating: 4.6,
          reviewCount: 89,
          publisher: "Nhà xuất bản Kinh Tế",
          publishedDate: new Date("2022-05-10"),
          pages: 356,
          language: "VI",
          edition: "Dịch Việt",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["lean startup", "khởi nghiệp", "MVP"],
          tags: ["lean-startup", "khoi-nghiep", "mvp"],
          sortOrder: 1,
        },
        {
          title: "Khởi Nghiệp Từ A đến Z",
          slug: "khoi-nghiep-tu-a-den-z",
          description: "Cẩm nang toàn diện cho người muốn khởi nghiệp, từ ý tưởng đến xây dựng công ty.",
          author: "Nguyễn Văn M",
          isbn: "9786042222225",
          price: 275000,
          discountPrice: 234000,
          currency: "VND",
          quantity: 33,
          sold: 78,
          coverImage: "https://example.com/khoi-nghiep-a-z.jpg",
          images: ["https://example.com/khoi-nghiep-a-z-1.jpg"],
          rating: 4.4,
          reviewCount: 56,
          publisher: "Nhà xuất bản Doanh Nghiệp",
          publishedDate: new Date("2023-08-15"),
          pages: 412,
          language: "VI",
          edition: "2nd edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: true,
          keywords: ["khởi nghiệp", "ý tưởng", "công ty"],
          tags: ["khoi-nghiep", "y-tuong", "cong-ty"],
          sortOrder: 2,
        },
        {
          title: "Xây Dựng Startup",
          slug: "xay-dung-startup",
          description: "Hướng dẫn từng bước xây dựng và phát triển startup trong môi trường cạnh tranh.",
          author: "Trần Thị N",
          isbn: "9786043333336",
          price: 285000,
          discountPrice: null,
          currency: "VND",
          quantity: 29,
          sold: 45,
          coverImage: "https://example.com/xay-dung-startup.jpg",
          images: ["https://example.com/xay-dung-startup-1.jpg"],
          rating: 4.3,
          reviewCount: 34,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2024-01-20"),
          pages: 334,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: true,
          isDiscount: false,
          keywords: ["startup", "xây dựng", "phát triển"],
          tags: ["startup", "xay-dung", "phat-trien"],
          sortOrder: 3,
        },
        {
          title: "Tìm Kiếm Ý Tưởng Khởi Nghiệp",
          slug: "tim-kiem-y-tuong-khoi-nghiep",
          description: "Hướng dẫn cách tìm kiếm và phát triển ý tưởng khởi nghiệp sáng tạo và khả thi.",
          author: "Lê Văn O",
          isbn: "9786044444447",
          price: 245000,
          discountPrice: 208000,
          currency: "VND",
          quantity: 37,
          sold: 62,
          coverImage: "https://example.com/tim-kiem-y-tuong.jpg",
          images: ["https://example.com/tim-kiem-y-tuong-1.jpg"],
          rating: 4.2,
          reviewCount: 41,
          publisher: "Nhà xuất bản Doanh Nghiệp",
          publishedDate: new Date("2023-11-08"),
          pages: 276,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["ý tưởng", "khởi nghiệp", "sáng tạo"],
          tags: ["y-tuong", "khoi-nghiep", "sang-tao"],
          sortOrder: 4,
        },
        {
          title: "Quản Lý Tài Chính Startup",
          slug: "quan-ly-tai-chinh-startup",
          description: "Chiến lược quản lý tài chính hiệu quả cho startup từ khởi đầu đến phát triển.",
          author: "Phạm Thị P",
          isbn: "9786045555558",
          price: 265000,
          discountPrice: null,
          currency: "VND",
          quantity: 24,
          sold: 38,
          coverImage: "https://example.com/quan-ly-tai-chinh.jpg",
          images: ["https://example.com/quan-ly-tai-chinh-1.jpg"],
          rating: 4.5,
          reviewCount: 29,
          publisher: "Nhà xuất bản Tài Chính",
          publishedDate: new Date("2024-02-14"),
          pages: 298,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["tài chính", "startup", "quản lý"],
          tags: ["tai-chinh", "startup", "quan-ly"],
          sortOrder: 5,
        },
        {
          title: "Marketing Cho Startup",
          slug: "marketing-cho-startup",
          description: "Chiến lược marketing hiệu quả với ngân sách hạn chế dành cho startup.",
          author: "Hoàng Văn Q",
          isbn: "9786046666669",
          price: 255000,
          discountPrice: 217000,
          currency: "VND",
          quantity: 31,
          sold: 54,
          coverImage: "https://example.com/marketing-startup.jpg",
          images: ["https://example.com/marketing-startup-1.jpg"],
          rating: 4.3,
          reviewCount: 36,
          publisher: "Nhà xuất bản Marketing",
          publishedDate: new Date("2023-09-25"),
          pages: 264,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["marketing", "startup", "ngân sách"],
          tags: ["marketing", "startup", "ngan-sach"],
          sortOrder: 6,
        },
      ],
      'quan-tri-doanh-nghiep': [
        {
          title: "Quản Trị Doanh Nghiệp Hiện Đại",
          slug: "quan-tri-doanh-nghiep-hien-dai",
          description: "Các nguyên tắc và phương pháp quản trị doanh nghiệp hiệu quả trong thời đại số.",
          author: "Nguyễn Văn R",
          isbn: "9786047777780",
          price: 385000,
          discountPrice: null,
          currency: "VND",
          quantity: 18,
          sold: 34,
          coverImage: "https://example.com/quan-tri-hien-dai.jpg",
          images: ["https://example.com/quan-tri-hien-dai-1.jpg"],
          rating: 4.7,
          reviewCount: 45,
          publisher: "Nhà xuất bản Kinh Tế",
          publishedDate: new Date("2023-04-12"),
          pages: 456,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["quản trị", "doanh nghiệp", "hiện đại"],
          tags: ["quan-tri", "doanh-nghiep", "hien-dai"],
          sortOrder: 1,
        },
        {
          title: "Lãnh Đạo Và Quản Lý",
          slug: "lanh-dao-va-quan-ly",
          description: "Kỹ năng lãnh đạo và quản lý đội ngũ hiệu quả trong môi trường doanh nghiệp.",
          author: "Trần Thị S",
          isbn: "9786048888891",
          price: 325000,
          discountPrice: 276000,
          currency: "VND",
          quantity: 22,
          sold: 41,
          coverImage: "https://example.com/lanh-dao-quan-ly.jpg",
          images: ["https://example.com/lanh-dao-quan-ly-1.jpg"],
          rating: 4.5,
          reviewCount: 38,
          publisher: "Nhà xuất bản Doanh Nghiệp",
          publishedDate: new Date("2023-07-08"),
          pages: 378,
          language: "VI",
          edition: "2nd edition",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: true,
          keywords: ["lãnh đạo", "quản lý", "đội ngũ"],
          tags: ["lanh-dao", "quan-ly", "doi-ngu"],
          sortOrder: 2,
        },
        {
          title: "Chiến Lược Kinh Doanh",
          slug: "chien-luoc-kinh-doanh",
          description: "Xây dựng và triển khai chiến lược kinh doanh cạnh tranh trong thị trường.",
          author: "Lê Văn T",
          isbn: "9786049999992",
          price: 355000,
          discountPrice: null,
          currency: "VND",
          quantity: 16,
          sold: 29,
          coverImage: "https://example.com/chien-luoc-kinh-doanh.jpg",
          images: ["https://example.com/chien-luoc-kinh-doanh-1.jpg"],
          rating: 4.6,
          reviewCount: 33,
          publisher: "Nhà xuất bản Kinh Tế",
          publishedDate: new Date("2024-01-25"),
          pages: 412,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: false,
          isNew: true,
          isDiscount: false,
          keywords: ["chiến lược", "kinh doanh", "cạnh tranh"],
          tags: ["chien-luoc", "kinh-doanh", "canh-tranh"],
          sortOrder: 3,
        },
        {
          title: "Quản Lý Chất Lượng",
          slug: "quan-ly-chat-luong",
          description: "Hệ thống quản lý chất lượng toàn diện cho doanh nghiệp hiện đại.",
          author: "Phạm Thị U",
          isbn: "9786040000003",
          price: 295000,
          discountPrice: 251000,
          currency: "VND",
          quantity: 25,
          sold: 47,
          coverImage: "https://example.com/quan-ly-chat-luong.jpg",
          images: ["https://example.com/quan-ly-chat-luong-1.jpg"],
          rating: 4.4,
          reviewCount: 28,
          publisher: "Nhà xuất bản Công Nghiệp",
          publishedDate: new Date("2023-10-18"),
          pages: 334,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["chất lượng", "quản lý", "hệ thống"],
          tags: ["chat-luong", "quan-ly", "he-thong"],
          sortOrder: 4,
        },
        {
          title: "Quản Lý Rủi Ro Doanh Nghiệp",
          slug: "quan-ly-rui-ro-doanh-nghiep",
          description: "Chiến lược nhận diện, đánh giá và quản lý rủi ro trong hoạt động kinh doanh.",
          author: "Hoàng Văn V",
          isbn: "9786041111115",
          price: 335000,
          discountPrice: null,
          currency: "VND",
          quantity: 19,
          sold: 36,
          coverImage: "https://example.com/quan-ly-rui-ro.jpg",
          images: ["https://example.com/quan-ly-rui-ro-1.jpg"],
          rating: 4.5,
          reviewCount: 31,
          publisher: "Nhà xuất bản Tài Chính",
          publishedDate: new Date("2024-02-08"),
          pages: 368,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["rủi ro", "doanh nghiệp", "quản lý"],
          tags: ["rui-ro", "doanh-nghiep", "quan-ly"],
          sortOrder: 5,
        },
        {
          title: "Đổi Mới Và Phát Triển",
          slug: "doi-moi-va-phat-trien",
          description: "Chiến lược đổi mới và phát triển bền vững cho doanh nghiệp trong kỷ nguyên số.",
          author: "Nguyễn Thị W",
          isbn: "9786042222226",
          price: 315000,
          discountPrice: 268000,
          currency: "VND",
          quantity: 21,
          sold: 39,
          coverImage: "https://example.com/doi-moi-phat-trien.jpg",
          images: ["https://example.com/doi-moi-phat-trien-1.jpg"],
          rating: 4.3,
          reviewCount: 27,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2023-12-05"),
          pages: 342,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["đổi mới", "phát triển", "bền vững"],
          tags: ["doi-moi", "phat-trien", "ben-vung"],
          sortOrder: 6,
        },
      ],
      'lap-trinh': [
        {
          title: "JavaScript Cơ Bản",
          slug: "javascript-co-ban",
          description: "Hướng dẫn từ A đến Z về ngôn ngữ lập trình JavaScript cho người mới bắt đầu.",
          author: "Nguyễn Văn X",
          isbn: "9786043333337",
          price: 225000,
          discountPrice: null,
          currency: "VND",
          quantity: 45,
          sold: 98,
          coverImage: "https://example.com/javascript-co-ban.jpg",
          images: ["https://example.com/javascript-co-ban-1.jpg"],
          rating: 4.4,
          reviewCount: 76,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2023-01-20"),
          pages: 298,
          language: "VI",
          edition: "3rd edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: false,
          keywords: ["JavaScript", "lập trình", "người mới"],
          tags: ["javascript", "lap-trinh", "nguoi-moi"],
          sortOrder: 1,
        },
        {
          title: "Python Cho Người Mới Bắt Đầu",
          slug: "python-cho-nguoi-moi-bat-dau",
          description: "Hướng dẫn lập trình Python từ cơ bản đến nâng cao với các ví dụ thực tế.",
          author: "Trần Thị Y",
          isbn: "9786044444448",
          price: 245000,
          discountPrice: 208000,
          currency: "VND",
          quantity: 38,
          sold: 87,
          coverImage: "https://example.com/python-co-ban.jpg",
          images: ["https://example.com/python-co-ban-1.jpg"],
          rating: 4.6,
          reviewCount: 92,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2023-06-15"),
          pages: 334,
          language: "VI",
          edition: "2nd edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: false,
          isDiscount: true,
          keywords: ["Python", "lập trình", "người mới"],
          tags: ["python", "lap-trinh", "nguoi-moi"],
          sortOrder: 2,
        },
        {
          title: "React.js Từ Cơ Bản Đến Nâng Cao",
          slug: "react-js-tu-co-ban-den-nang-cao",
          description: "Hướng dẫn đầy đủ về React.js, từ component cơ bản đến state management và hooks.",
          author: "Lê Văn Z",
          isbn: "9786045555559",
          price: 285000,
          discountPrice: null,
          currency: "VND",
          quantity: 32,
          sold: 65,
          coverImage: "https://example.com/react-js.jpg",
          images: ["https://example.com/react-js-1.jpg"],
          rating: "4.5",
          reviewCount: 54,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2024-01-10"),
          pages: 412,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: true,
          isDiscount: false,
          keywords: ["React.js", "frontend", "JavaScript"],
          tags: ["react-js", "frontend", "javascript"],
          sortOrder: 3,
        },
        {
          title: "Node.js Và Express.js",
          slug: "node-js-va-express-js",
          description: "Xây dựng ứng dụng web backend với Node.js và Express.js từ cơ bản đến thực tế.",
          author: "Phạm Thị AA",
          isbn: "9786046666670",
          price: 265000,
          discountPrice: 225000,
          currency: "VND",
          quantity: 29,
          sold: 52,
          coverImage: "https://example.com/node-express.jpg",
          images: ["https://example.com/node-express-1.jpg"],
          rating: 4.3,
          reviewCount: 41,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2023-09-08"),
          pages: 356,
          language: "VI",
          edition: "1st edition",
          format: "paperback",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["Node.js", "Express.js", "backend"],
          tags: ["node-js", "express-js", "backend"],
          sortOrder: 4,
        },
        {
          title: "Lập Trình Hướng Đối Tượng",
          slug: "lap-trinh-huong-doi-tuong",
          description: "Nguyên tắc lập trình hướng đối tượng với các ngôn ngữ phổ biến như Java, C++, C#.",
          author: "Hoàng Văn BB",
          isbn: "9786047777781",
          price: 275000,
          discountPrice: null,
          currency: "VND",
          quantity: 26,
          sold: 48,
          coverImage: "https://example.com/oop.jpg",
          images: ["https://example.com/oop-1.jpg"],
          rating: 4.4,
          reviewCount: 35,
          publisher: "Nhà xuất bản Giáo Dục",
          publishedDate: new Date("2024-02-20"),
          pages: 324,
          language: "VI",
          edition: "2nd edition",
          format: "paperback",
          status: "active",
          isFeatured: true,
          isNew: true,
          isDiscount: false,
          keywords: ["OOP", "hướng đối tượng", "lập trình"],
          tags: ["oop", "huong-doi-tuong", "lap-trinh"],
          sortOrder: 5,
        },
        {
          title: "Cấu Trúc Dữ Liệu Và Giải Thuật",
          slug: "cau-truc-du-lieu-va-giai-thuat",
          description: "Hiểu biết sâu sắc về cấu trúc dữ liệu và giải thuật lập trình.",
          author: "Nguyễn Thị CC",
          isbn: "9786048888892",
          price: 295000,
          discountPrice: 251000,
          currency: "VND",
          quantity: 23,
          sold: 39,
          coverImage: "https://example.com/data-structures.jpg",
          images: ["https://example.com/data-structures-1.jpg"],
          rating: 4.7,
          reviewCount: 28,
          publisher: "Nhà xuất bản Công Nghệ",
          publishedDate: new Date("2023-11-15"),
          pages: 398,
          language: "VI",
          edition: "1st edition",
          format: "hardcover",
          status: "active",
          isFeatured: false,
          isNew: false,
          isDiscount: true,
          keywords: ["cấu trúc dữ liệu", "giải thuật", "lập trình"],
          tags: ["cau-truc-du-lieu", "giai-thuat", "lap-trinh"],
          sortOrder: 6,
        },
      ],
    };

    // Process each category
    for (const subcategory of subcategories) {
      const categorySlug = subcategory.slug;
      const categoryId = subcategory._id;

      if (booksData[categorySlug]) {
        console.log(`\n📚 Seeding books for category: ${subcategory.name} (${categorySlug})`);

        // Clean existing books in this category
        await Book.deleteMany({ categoryId });
        console.log(`🗑️ Cleared existing books in ${subcategory.name}`);

        // Add categoryId to each book
        const booksWithCategoryId = booksData[categorySlug].map(book => ({
          ...book,
          categoryId
        }));

        // Insert books
        await Book.insertMany(booksWithCategoryId);
        console.log(`✅ Inserted ${booksWithCategoryId.length} books for ${subcategory.name}`);
      }
    }

    console.log("\n🎉 All books seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed error:", error);
    process.exit(1);
  }
};

seedBooksForAllCategories();
